// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqwXevwoUAxf2oC7LAKSeFxP-CJ2W_3k',
    appId: '1:875733790804:web:aaa3fa610670020b7e3dc1',
    messagingSenderId: '875733790804',
    projectId: 'flutter-85128',
    authDomain: 'flutter-85128.firebaseapp.com',
    storageBucket: 'flutter-85128.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKyctAEbZLmJNFj5yLIWdBu2XAdS0aXk',
    appId: '1:875733790804:android:2c8b1dfa943cca6b7e3dc1',
    messagingSenderId: '875733790804',
    projectId: 'flutter-85128',
    storageBucket: 'flutter-85128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBssUZo3WD7vaa2qTekplSgttt77dxKiqY',
    appId: '1:875733790804:ios:16f0553810fa27ed7e3dc1',
    messagingSenderId: '875733790804',
    projectId: 'flutter-85128',
    storageBucket: 'flutter-85128.appspot.com',
    iosBundleId: 'com.vofforila.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBssUZo3WD7vaa2qTekplSgttt77dxKiqY',
    appId: '1:875733790804:ios:16f0553810fa27ed7e3dc1',
    messagingSenderId: '875733790804',
    projectId: 'flutter-85128',
    storageBucket: 'flutter-85128.appspot.com',
    iosBundleId: 'com.vofforila.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTqwXevwoUAxf2oC7LAKSeFxP-CJ2W_3k',
    appId: '1:875733790804:web:845ac3d907b63d8c7e3dc1',
    messagingSenderId: '875733790804',
    projectId: 'flutter-85128',
    authDomain: 'flutter-85128.firebaseapp.com',
    storageBucket: 'flutter-85128.appspot.com',
  );
}
