// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIvQKBeruvLdV74ySuHFPWHIgWw9uzy5A',
    appId: '1:481400981162:web:383fb53435eedc2568f2d3',
    messagingSenderId: '481400981162',
    projectId: 'projects-175f8',
    authDomain: 'projects-175f8.firebaseapp.com',
    databaseURL: 'https://projects-175f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projects-175f8.appspot.com',
    measurementId: 'G-MF9LGR4C33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnj7VY_JkOx7zBXadbEEOJYCNxPYAKROM',
    appId: '1:481400981162:android:434e58e4929661b068f2d3',
    messagingSenderId: '481400981162',
    projectId: 'projects-175f8',
    databaseURL: 'https://projects-175f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projects-175f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABGyaLfjadKG8AeQa36Evf4GJSWsC5waU',
    appId: '1:481400981162:ios:5c6a947812116bb168f2d3',
    messagingSenderId: '481400981162',
    projectId: 'projects-175f8',
    databaseURL: 'https://projects-175f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projects-175f8.appspot.com',
    iosBundleId: 'com.vofforila.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABGyaLfjadKG8AeQa36Evf4GJSWsC5waU',
    appId: '1:481400981162:ios:5c6a947812116bb168f2d3',
    messagingSenderId: '481400981162',
    projectId: 'projects-175f8',
    databaseURL: 'https://projects-175f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projects-175f8.appspot.com',
    iosBundleId: 'com.vofforila.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIvQKBeruvLdV74ySuHFPWHIgWw9uzy5A',
    appId: '1:481400981162:web:2bece103e07dd99868f2d3',
    messagingSenderId: '481400981162',
    projectId: 'projects-175f8',
    authDomain: 'projects-175f8.firebaseapp.com',
    databaseURL: 'https://projects-175f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projects-175f8.appspot.com',
    measurementId: 'G-HMH9HXWTL4',
  );
}
